baseURL = 'https://aravindh.net/notes/'
languageCode = 'en-us'
title = 'Aravindh'

summaryLength = 40

[params]
headerTitle = 'Aravindh'
introTitle = 'Welcome to my digital garden.'
introText = 'I write about computers, my wood working adventures and anything that captures my fascination enough to obsess over for a time.'

[frontmatter]
lastmod = [':fileModTime', 'lastmod', 'date', 'publishDate']

[taxonomies]
tag = 'tags'
