baseURL = 'https://aravindh.net/notes/'
languageCode = 'en-us'
title = 'Aravindh'

summaryLength = 40

[pagination]
pagerSize = 20

[params]
headerTitle = 'Aravindh'
introTitle = 'Welcome to my digital garden.'
introText = 'I write about computers, my wood working adventures and anything that captures my fascination enough to obsess over for a time.'
description = 'Welcome to my digital garden. I write about computers, my wood working adventures and anything that captures my fascination enough to obsess over for a time.'

# Optional: put a share image under `static/` and set this to its path, e.g. "/images/og.png"
ogImage = ''

[frontmatter]
lastmod = ['lastmod', ':fileModTime', 'date', 'publishDate']

[taxonomies]
tag = 'tags'
