[sentinel]
content_dir = "content"
log_file = "site-sentinel.log"

[deploy]
# Path relative to $HOME, or absolute
ssh_key = "~/.ssh/id_rsa_aravindh.net"
ssh_target = "root@49.12.190.41"
dest_dir = "/home/caddy/www/notes/"
